# Generated by Django 3.2 on 2021-04-19 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.datetime_safe.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_Name', models.CharField(default='none', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_cat_name', models.CharField(default='sub cat', max_length=20)),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_Name', models.CharField(default='product name', max_length=20)),
                ('product_Price', models.IntegerField(default=0)),
                ('product_Image', models.URLField(default='Null', max_length=150)),
                ('product_Stock', models.BooleanField(default=True)),
                ('sub_cat', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.subcat')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_Status', models.CharField(default='Success', max_length=20)),
                ('total_Amount', models.FloatField(default=0.0, max_length=10)),
                ('order_Shipping_Charges', models.FloatField(default=0.0, max_length=10)),
                ('order_Tax', models.FloatField(default=0.0, max_length=10)),
                ('order_Mobile', models.IntegerField(default=0)),
                ('order_Address', models.CharField(default='order Address', max_length=50)),
                ('order_Country', models.CharField(default='Pakistan', max_length=20)),
                ('order_PayMethod', models.CharField(default='COD', max_length=20)),
                ('order_TrackId', models.IntegerField(default=0)),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price_ht', models.FloatField(blank=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.product')),
            ],
        ),
    ]
