# Generated by Django 3.2 on 2021-04-20 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_product_sub_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='price_ht',
            new_name='price',
        ),
    ]
