# Generated by Django 3.2 on 2021-05-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_product_product_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_Description',
            field=models.TextField(default='description'),
        ),
    ]
