# Generated by Django 3.2 on 2021-05-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_product_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcat',
            name='cat_Image',
            field=models.URLField(default='Null', max_length=150),
        ),
    ]
